# Generated by Django 5.2 on 2025-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST Registration Number', max_length=15, null=True),
        ),
    ]
