# Generated by Django 5.2 on 2025-04-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_gst_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateField()),
                ('grade', models.CharField(choices=[('M20', 'M20'), ('M25', 'M25'), ('M30', 'M30')], max_length=5)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in cubic meters (m³)', max_digits=8)),
                ('site_location', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('stock_validated', models.BooleanField(default=False, help_text='Indicates if stock levels have been validated')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concrete_deliveries', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Concrete Delivery',
                'verbose_name_plural': 'Concrete Deliveries',
                'ordering': ['-delivery_date'],
            },
        ),
    ]
