# Generated by Django 5.2 on 2025-04-22 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_concretedelivery'),
        ('materials', '0002_purchaseorder_inventory_updated_inventoryentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretedelivery',
            name='inventory_deducted',
            field=models.BooleanField(default=False, help_text='Indicates if inventory has been deducted'),
        ),
        migrations.CreateModel(
            name='MixRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grade', models.CharField(choices=[('M20', 'M20'), ('M25', 'M25'), ('M30', 'M30')], max_length=5)),
                ('qty_per_m3', models.DecimalField(decimal_places=2, help_text='Quantity of material needed per cubic meter of concrete', max_digits=8)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mix_ratios', to='materials.material')),
            ],
            options={
                'verbose_name': 'Mix Ratio',
                'verbose_name_plural': 'Mix Ratios',
                'unique_together': {('grade', 'material')},
            },
        ),
    ]
