# Generated by Django 5.2 on 2025-04-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_options_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='risk_last_updated',
            field=models.DateTimeField(blank=True, help_text='When risk score was last updated', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_notes',
            field=models.TextField(blank=True, help_text='Notes about risk factors and payment behavior', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='risk_score',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], default='LOW', help_text='Risk assessment based on payment history', max_length=10),
        ),
    ]
