# Generated by Django 5.2 on 2025-04-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_risk_last_updated_customer_risk_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='due_date',
            field=models.DateField(blank=True, help_text='Payment due date for this delivery', null=True),
        ),
    ]
