# Generated by Django 5.2 on 2025-04-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_delivery_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretedelivery',
            name='grade',
            field=models.CharField(choices=[('M5', 'M5'), ('M7.5', 'M7.5'), ('M10', 'M10'), ('M15', 'M15'), ('M20', 'M20'), ('M25', 'M25'), ('M30', 'M30'), ('M35', 'M35'), ('M40', 'M40'), ('M45', 'M45'), ('M50', 'M50'), ('M55', 'M55'), ('M60', 'M60'), ('M65', 'M65'), ('M70', 'M70')], max_length=5),
        ),
        migrations.AlterField(
            model_name='mixratio',
            name='grade',
            field=models.CharField(choices=[('M5', 'M5'), ('M7.5', 'M7.5'), ('M10', 'M10'), ('M15', 'M15'), ('M20', 'M20'), ('M25', 'M25'), ('M30', 'M30'), ('M35', 'M35'), ('M40', 'M40'), ('M45', 'M45'), ('M50', 'M50'), ('M55', 'M55'), ('M60', 'M60'), ('M65', 'M65'), ('M70', 'M70')], max_length=5),
        ),
    ]
