# Generated by Django 5.2 on 2025-04-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_concretedelivery_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concretedelivery',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Unique invoice number for this delivery', max_length=50, unique=True),
        ),
    ]
