services:
  - type: web
    name: amaravathi-rmbmp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn amaravathi_rmbmp.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: amaravathi_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: amaravathi_rmbmp.settings

databases:
  - name: amaravathi_db
    databaseName: amaravathi
    user: amaravathi
    plan: free 