# Generated by Django 5.2 on 2025-04-23 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='payment_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly')], default='monthly', help_text='Frequency of salary payments', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_due_day',
            field=models.PositiveIntegerField(default=5, help_text='Day of the month (1-31) when salary is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
