# Generated by Django 5.2 on 2025-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_payment_cycle_employee_salary_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecord',
            name='expense_id',
            field=models.IntegerField(blank=True, help_text='ID of the expense entry created for this salary', null=True),
        ),
    ]
