# Generated by Django 5.2 on 2025-04-22 03:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='inventory_updated',
            field=models.BooleanField(default=False, help_text='Flag to track if inventory was updated'),
        ),
        migrations.CreateModel(
            name='InventoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('entry_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=3)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference_type', models.CharField(choices=[('PURCHASE', 'Purchase Order'), ('SALE', 'Sale Order'), ('ADJUSTMENT', 'Manual Adjustment'), ('RETURN', 'Return'), ('OTHER', 'Other')], max_length=20)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID of the related document', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='materials.material')),
            ],
            options={
                'verbose_name_plural': 'Inventory Entries',
                'ordering': ['-date'],
            },
        ),
    ]
