# Generated by Django 5.2 on 2025-04-24 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_purchaseorder_inventory_updated_inventoryentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='current_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
