# Generated by Django 5.2 on 2025-04-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_alter_material_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for payment, leave blank if no credit terms', null=True),
        ),
    ]
