# Generated by Django 5.2 on 2025-04-22 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_purchase_invoice_file_purchase_invoice_file_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='supplier',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(default=12132024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default=678954312, max_length=15),
            preserve_default=False,
        ),
    ]
