# Generated by Django 5.2 on 2025-04-22 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('BANK', 'Bank Transfer'), ('CREDIT', 'Credit'), ('UPI', 'UPI'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('payment_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, help_text='Cheque number, transaction ID, etc.', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
