# Generated by Django 5.2 on 2025-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0004_supplierpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayment',
            name='due_date',
            field=models.DateField(blank=True, help_text='Required only for credit payments', null=True),
        ),
    ]
