# Generated by Django 5.2 on 2025-04-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_supplierpayment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(blank=True, help_text='Leave blank if no credit terms', null=True),
        ),
    ]
