# Generated by Django 5.2 on 2025-04-23 05:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_options_alter_delivery_options_and_more'),
        ('expenses', '0002_initial'),
        ('materials', '0002_purchaseorder_inventory_updated_inventoryentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name or identifier of the vehicle', max_length=100)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('mixer', 'Concrete Mixer'), ('car', 'Car'), ('bike', 'Bike'), ('other', 'Other')], max_length=20)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(blank=True, help_text='Manufacturer of the vehicle', max_length=50, null=True)),
                ('model', models.CharField(blank=True, help_text='Model of the vehicle', max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, help_text='Manufacturing year', null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AddField(
            model_name='expense',
            name='associated_delivery',
            field=models.ForeignKey(blank=True, help_text='Associated delivery (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='customers.delivery'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('fuel', 'Fuel'), ('office', 'Office'), ('materials', 'Materials'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('salary', 'Salary'), ('other', 'Other')], default=12345, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='material',
            field=models.ForeignKey(blank=True, help_text='Related material (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='materials.material'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('upi', 'UPI'), ('cheque', 'Cheque')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Invoice or reference number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, help_text='Related vehicle (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.vehicle'),
        ),
    ]
