# Generated by Django 5.2 on 2025-04-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_vehicle_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='default_type',
            field=models.CharField(choices=[('vehicle', 'Vehicle'), ('fuel', 'Fuel'), ('office', 'Office'), ('materials', 'Materials'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('rent', 'Rent'), ('salary', 'Salary'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
